version: '3.1'

services:
  nodejs:
    build: .
    container_name: nodejs
    depends_on: 
      - "db"
    env_file: 
     - '.env.test'
    environment:
      - TB_DB_USERNAME=$TB_DB_USERNAME
      - TB_DB_PASSWORD=$TB_DB_PASSWORD
      - TB_DB_HOSTNAME=db
      - TB_DB_PORT=$TB_DB_PORT
      - TB_DB_NAME=$TB_DB_NAME
    working_dir: '/usr/src/app'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
    command: > 
      bash -c "npm install
      && npm run start
      && npm run test"
    ports:
      - ${PORT}:${PORT}

  db:
    image: mongo
    container_name: db
    ports:
      - ${TB_DB_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$TB_DB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$TB_DB_PASSWORD
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
