version: '3.1'

services:
  nodejs:
    build: .
    container_name: nodejs
    environment:
      - TB_DB_USERNAME=$TB_DB_USERNAME
      - TB_DB_PASSWORD=$TB_DB_PASSWORD
      - TB_DB_HOSTNAME=db
      - TB_DB_PORT=$TB_DB_PORT
      - TB_DB_NAME=$TB_DB_NAME
    working_dir: '/usr/src/app'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
    command: > 
      bash -c "npm install
      && npm run db
      && npm run start"
    ports:
      - ${PORT}:${PORT}